### ISSUE TITLE
Synchronizing Tickets in different Github Projects

### ISSUE THREAD

**Issue by dvvanessastoiber** [datavisyn/github-workflows#10]
Based on the new Deployment and QA Process definition, we need a workflow/GA that automatically moves the tickets to the correct columns in the respective boards. This is most important for QA tickets, that are planned within a sprint, created within the application Github project (e.g. [sightline](https://github.com/orgs/datavisyn/projects/19)) and added to the [testing Github project](https://github.com/orgs/datavisyn/projects/8/views/4) as well:

* Note that these tickets have the label `type: qa`
* While the QA team is testing, they manually move the ticket to "In Progress" in the [testing Github project](https://github.com/orgs/datavisyn/projects/8/views/4)  --> the ticket should then be transferred automatically to "In Progress" in the application Github project as well
* Once the QA team is done, they will move the ticket manually to "Done" in the [testing Github project](https://github.com/orgs/datavisyn/projects/8/views/4) --> the ticket should then be transferred automatically to "Review" in the application Github project
* The PO takes the ticket from "Review", derives his/her measures, and moves the ticket to "Closed" in the application Github project --> the ticket should then be transferred automatically to "Closed" in the [testing Github project](https://github.com/orgs/datavisyn/projects/8/views/4) as well

If any of this is unclear, please feel free to ping me!

**Comment by dvviktordelev** [comment]
syncing issues in this manner doesn't seem to be supported (yet)

actions I found managing issues:
from a verified creator: this one add issue to the default column only.
https://github.com/marketplace/actions/add-to-github-projects

from non-verified:
https://github.com/marketplace/actions/issue-sync-action
https://github.com/marketplace/actions/move-issues-to-column

**Comment by puehringer** [comment]
The core team has decided to not do this because it is quite complex and not worth the investment. The proposed way is to simply use the QA meeting to do this.
