### ISSUE TITLE
Output of lint step in product build not handled correctly

### ISSUE THREAD

**Issue by dvvanessastoiber** [datavisyn/github-workflows#16]
### Summary
In the prepare-build job, the `lint dockerfiles` step fails without showing the actual error even though corresponding logs were added to the hadolint script. Despite facing an actual lint error in the Dockerfile, the `show dockerfile lint error` step is just omitted. This can be seen in the screenshot below:
![image](https://github.com/datavisyn/github-workflows/assets/52395160/74fe0b25-7bed-47e6-bb54-40ee769af7f4)

### Expected Behavior
We would expect to see more logs in the lint step and especially the `show dockerfile lint error` should never be omitted if errors occur.

Corresponding Github Action: https://github.com/datavisyn/github-workflows/tree/new_deployment/.github/actions/lint-docker

**Comment by dvviktordelev** [comment]
https://github.com/datavisyn/github-workflows/pull/34
