### ISSUE TITLE
Workflows: Fix deprecation warnings

### ISSUE THREAD

**Issue by dvvanessastoiber** [datavisyn/github-workflows#81]
This error occurs in the build workflow. Please update all occurrences of artifact actions to v4 and check if any changes in the workflows are required. Thank you!
![Image](https://github.com/user-attachments/assets/adf8b2be-8c5b-473d-b39b-0546d0c438a0)

**Comment by dvviktordelev** [comment]
fixed, [PR](https://github.com/datavisyn/github-workflows/pull/84)
